import { Color } from '@signozhq/design-tokens';
import tailwindAnimate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ['class'],
	content: ['./src/**/*.{js,ts,jsx,tsx}'],
	theme: {
		extend: {
			fontFamily: {
				sans: 'var(--font-sans)',
				serif: 'var(--font-serif)',
				mono: 'var(--font-mono)',
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			colors: {
				background: 'var(--background)',
				foreground: 'var(--foreground)',
				border: 'var(--border)',
				input: 'var(--input)',
				ring: 'var(--ring)',
				primary: {
					DEFAULT: 'var(--primary)',
					foreground: 'var(--primary-foreground)',
				},
				secondary: {
					DEFAULT: 'var(--secondary)',
					foreground: 'var(--secondary-foreground)',
				},
				destructive: {
					DEFAULT: 'var(--destructive)',
					foreground: 'var(--destructive-foreground)',
				},
				muted: {
					DEFAULT: 'var(--muted)',
					foreground: 'var(--muted-foreground)',
				},
				accent: {
					DEFAULT: 'var(--accent)',
					foreground: 'var(--accent-foreground)',
				},
				card: {
					DEFAULT: 'var(--card)',
					foreground: 'var(--card-foreground)',
				},
				popover: {
					DEFAULT: 'var(--popover)',
					foreground: 'var(--popover-foreground)',
				},
				chart: {
					1: 'var(--chart-1)',
					2: 'var(--chart-2)',
					3: 'var(--chart-3)',
					4: 'var(--chart-4)',
					5: 'var(--chart-5)',
				},
				sidebar: {
					DEFAULT: 'var(--sidebar)',
					foreground: 'var(--sidebar-foreground)',
					primary: {
						DEFAULT: 'var(--sidebar-primary)',
						foreground: 'var(--sidebar-primary-foreground)',
					},
					accent: {
						DEFAULT: 'var(--sidebar-accent)',
						foreground: 'var(--sidebar-accent-foreground)',
					},
					border: 'var(--sidebar-border)',
					ring: 'var(--sidebar-ring)',
				},
			},
			boxShadow: {
				'2xs': 'var(--shadow-2xs)',
				xs: 'var(--shadow-xs)',
				sm: 'var(--shadow-sm)',
				DEFAULT: 'var(--shadow)',
				md: 'var(--shadow-md)',
				lg: 'var(--shadow-lg)',
				xl: 'var(--shadow-xl)',
				'2xl': 'var(--shadow-2xl)',
			},
		},
	},
	plugins: [
		tailwindAnimate,
		function ({ addBase }) {
			addBase({
				':root': {
					'--background': Color.BG_VANILLA_200,
					'--foreground': Color.TEXT_INK_400,
					'--card': Color.BG_VANILLA_100,
					'--card-foreground': Color.TEXT_INK_400,
					'--popover': Color.BG_VANILLA_100,
					'--popover-foreground': Color.TEXT_INK_400,
					'--primary': Color.BG_ROBIN_500,
					'--primary-foreground': Color.TEXT_VANILLA_100,
					'--ring': Color.BG_ROBIN_500,
					'--sidebar-primary': Color.BG_ROBIN_500,
					'--sidebar-ring': Color.BG_ROBIN_500,
					'--secondary': Color.BG_VANILLA_300,
					'--secondary-foreground': Color.TEXT_SLATE_400,
					'--muted': Color.BG_VANILLA_300,
					'--muted-foreground': Color.TEXT_SLATE_50,
					'--accent': Color.BG_AQUA_100,
					'--accent-foreground': Color.TEXT_SLATE_400,
					'--destructive': Color.BG_CHERRY_500,
					'--destructive-foreground': Color.TEXT_VANILLA_100,
					'--border': Color.BG_SLATE_400,
					'--input': Color.BG_SLATE_400,
					'--chart-1': Color.BG_ROBIN_500,
					'--chart-2': Color.BG_ROBIN_600,
					'--chart-3': Color.BG_SLATE_300,
					'--chart-4': Color.BG_SLATE_400,
					'--chart-5': Color.BG_SLATE_500,
					'--sidebar': Color.BG_VANILLA_300,
					'--sidebar-foreground': Color.TEXT_INK_400,
					'--sidebar-primary-foreground': Color.TEXT_VANILLA_100,
					'--sidebar-accent': Color.BG_AQUA_100,
					'--sidebar-accent-foreground': Color.TEXT_SLATE_400,
					'--sidebar-border': Color.BG_SLATE_400,
					'--radius': '0.25rem',
					'--font-sans': 'Inter, sans-serif',
					'--font-serif': 'Open Sans, sans-serif',
					'--font-mono': 'Geist Mono, monospace',
				},
				'.dark': {
					'--background': Color.BG_INK_500,
					'--foreground': Color.TEXT_VANILLA_400,
					'--card': Color.BG_INK_400,
					'--card-foreground': Color.TEXT_VANILLA_100,
					'--popover': Color.BG_INK_400,
					'--popover-foreground': Color.TEXT_VANILLA_100,
					'--secondary': Color.BG_SLATE_500,
					'--secondary-foreground': Color.TEXT_VANILLA_400,
					'--muted': Color.BG_SLATE_500,
					'--muted-foreground': Color.TEXT_VANILLA_400,
					'--accent': Color.BG_SLATE_300,
					'--accent-foreground': Color.TEXT_VANILLA_100,
					'--destructive': Color.BG_CHERRY_500,
					'--destructive-foreground': Color.TEXT_INK_500,
					'--border': Color.BG_SLATE_400,
					'--input': Color.BG_SLATE_300,
					'--chart-1': Color.BG_ROBIN_400,
					'--chart-2': Color.BG_ROBIN_500,
					'--chart-3': Color.BG_ROBIN_600,
					'--chart-4': Color.BG_SLATE_200,
					'--chart-5': Color.BG_SLATE_300,
					'--sidebar': Color.BG_SLATE_500,
					'--sidebar-foreground': Color.TEXT_VANILLA_400,
					'--sidebar-primary-foreground': Color.TEXT_INK_500,
					'--sidebar-accent': Color.BG_SLATE_400,
					'--sidebar-accent-foreground': Color.TEXT_VANILLA_400,
					'--sidebar-border': Color.BG_SLATE_500,
				},
				'[data-theme-color="blue"]': {
					'--primary': Color.BG_ROBIN_500,
					'--primary-foreground': Color.TEXT_VANILLA_100,
					'--ring': Color.BG_ROBIN_500,
					'--sidebar-primary': Color.BG_ROBIN_500,
					'--sidebar-ring': Color.BG_ROBIN_500,
				},
				'.dark[data-theme-color="blue"]': {
					'--primary': Color.BG_ROBIN_400,
					'--primary-foreground': Color.TEXT_INK_500,
					'--ring': Color.BG_ROBIN_400,
					'--sidebar-primary': Color.BG_ROBIN_400,
					'--sidebar-ring': Color.BG_ROBIN_400,
				},
			});
		},
	],
};
