name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: release
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js 24.x
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"

      - name: Install Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm install

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm run build --filter=docs^...

      - name: Publish to npm
        if: ${{ steps.release.outputs.release_created }}
        run: pnpm -r publish --no-git-checks --filter=docs^...
        env:
          NPM_CONFIG_PROVENANCE: true
